

function myExample() {
    var box = document.getElementById('format');
    var format = box.options[box.selectedIndex].text;
    var sample = "";
    if (format == 'FASTA Sequence'){
        sample = ">Sample1:\nMKNFFAVCIIPLVVTWSATASAKEGIYITGKAGTSVVNVYGINSTFSQEEIVNGHATLPDRTKGVFGGGVAIGYDFYDPFQLPVRLELDTTFRGETDAKGGQDIIAFGQPVHINVKNQVRMTTYIVNGYYDFHNSTAFTPYISAGVGLAHVKLSNNTIPVGFGINETLSASKNNFAWGAGIGAKYAVTDNIMIDASYKYINAGKVSISKNHYAGDEHTAYDADTKAASNDFMLGITYAF\n"
        sample+=">Sample2\n"
        sample+="MIEVGRIIAERYKILSYVGKGGMQDVYKVLDLKLDLDLALKTPLPGLESKRFLKSAKIAAKINHHNIAKT"
        sample+="FDYVEDNGNIFLAEEFVEGENLEEKLRHFDFLDPHYGACILHNLAKGIMASHKADVIHRDLKPSNVMVSG"
        sample+= "GVQISNLKITDFGIATLTQELFDEAAASGDLTRSTSGTIKGALPFMSPELMFGKKGKPIEASTDIWPLGA"       
        sample+= "MMFKLLTGDYPFGVYLDAAVNVKTKNRMEWPTFMTANPQYQSLSQDLQKIVDKCLSYDSDKRPTAETLVK"       
        sample+= "ACETLCYLSEERHVGRVNNLIQGGISGFIDGTPSNSFFSMESVYGSRYPNTSTRNTVCYSTFDGHPWPRAHPVILWKD"       
        
    } else if (format == 'GenBank Identifier'){
        sample = "29138558, 29140401"
    } else if (format == 'Uniprot Identifier'){
        sample = "Q8Z939, Q8Z111"
    }
    
    document.getElementById('text').value=sample
    return false;
}

/*

*/
