# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 17:43
from __future__ import unicode_literals

import adhesin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FASTA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=70)),
                ('sequence', models.CharField(max_length=200)),
                ('ans', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cls', models.BooleanField(default=False)),
                ('rank', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('address', models.IntegerField(primary_key=True, serialize=False)),
                ('pub_date', models.CharField(default=b'm_06/d_16/', max_length=12)),
                ('perPage', models.IntegerField(default=10)),
                ('algo', models.CharField(default='R', max_length=1)),
                ('upFile', models.FileField(upload_to=adhesin.models.user_directory_path)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.CharField(max_length=10)),
                ('algo', models.CharField(default='R', max_length=1)),
            ],
        ),
    ]
