# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='')),
                ('email', models.EmailField(max_length=254)),
                ('country_cd', models.CharField(max_length=2)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='filedata',
            name='pub_date',
            field=models.CharField(default=b'06_21_', max_length=12),
        ),
        migrations.AlterField(
            model_name='proteindata',
            name='pub_date',
            field=models.CharField(default=b'06_21_', max_length=10),
        ),
    ]
