# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesin', '0003_auto_20160621_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='mode',
            field=models.CharField(default='t', max_length=1),
            preserve_default=False,
        ),
    ]
