# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesin', '0004_user_details_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasta',
            name='address',
            field=models.CharField(default='1', max_length=15),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='pub_date',
            field=models.CharField(default=b'06_23_', max_length=12),
        ),
        migrations.AlterField(
            model_name='proteindata',
            name='pub_date',
            field=models.CharField(default=b'06_23_', max_length=10),
        ),
    ]
