# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesin', '0007_auto_20160625_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='ip',
        ),
        migrations.AddField(
            model_name='filedata',
            name='inFormat',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='proteindata',
            name='inFormat',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='user_details',
            name='org',
            field=models.CharField(default='unknown', max_length=40),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='pub_date',
            field=models.CharField(default=b'07_02_', max_length=12),
        ),
        migrations.AlterField(
            model_name='proteindata',
            name='pub_date',
            field=models.CharField(default=b'07_02_', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='address',
            field=models.CharField(max_length=40),
        ),
    ]
