# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesin', '0009_auto_20160705_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='pub_date',
            field=models.CharField(default=b'07_09_', max_length=12),
        ),
        migrations.AlterField(
            model_name='proteindata',
            name='pub_date',
            field=models.CharField(default=b'07_09_', max_length=10),
        ),
    ]
