# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesin', '0010_auto_20160709_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasta',
            name='header',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fasta',
            name='sequence',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='pub_date',
            field=models.CharField(default=b'07_13_', max_length=12),
        ),
        migrations.AlterField(
            model_name='proteindata',
            name='pub_date',
            field=models.CharField(default=b'07_13_', max_length=10),
        ),
    ]
